on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: macos
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: cristinagnlez04/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: share.multiplica.com
        FTP_USERNAME: sharemx
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        
